/**
 * Markdown docs generator — emits `reference.md` (at the package root)
 * describing every node and meta element from the compiled registry.
 */

import type {
  AttributeSpec,
  CompiledNodeDefinition,
} from "../registry/defineNode.ts";
import type { CompiledMetaDefinition } from "../registry/defineMeta.ts";
import { walkRegistry } from "./walkRegistry.ts";

export function generateNodesMd(): string {
  const registry = walkRegistry();
  const out: string[] = [];

  out.push("# Builder XML Reference");
  out.push("");
  out.push(
    "> Generated by `packages/builder/src/codegen/docs.ts`. Edit the registry, not this file.",
  );
  out.push("");
  out.push(
    "Document namespace: `urn:slideglance:builder:v1`. See [README](../README.md) for usage.",
  );
  out.push("");
  out.push("## Contents");
  out.push("");
  out.push("- [Nodes](#nodes)");
  for (const n of registry.nodes) {
    out.push(`  - [\`<${n.tag}>\`](#${anchor(n.tag)})`);
  }
  out.push("- [Meta Elements](#meta-elements)");
  for (const m of registry.meta) {
    out.push(`  - [\`<${m.tag}>\`](#${anchor(m.tag)})`);
  }
  out.push("");

  out.push("## Nodes");
  out.push("");
  for (const n of registry.nodes) {
    out.push(...renderNode(n));
  }

  out.push("## Meta Elements");
  out.push("");
  for (const m of registry.meta) {
    out.push(...renderMeta(m));
  }

  return out.join("\n");
}

function renderNode(node: CompiledNodeDefinition): string[] {
  const out: string[] = [];
  out.push(`### \`<${node.tag}>\``);
  out.push("");
  if (node.description) {
    out.push(node.description);
    out.push("");
  }

  const attrEntries = Object.entries(node.attributes).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  if (attrEntries.length > 0) {
    out.push("**Attributes**");
    out.push("");
    out.push("| Name | Type | Required | Description |");
    out.push("|---|---|---|---|");
    for (const [name, spec] of attrEntries) {
      out.push(formatAttrRow(name, spec));
    }
    out.push("");
  }

  if (Object.keys(node.children).length > 0) {
    out.push("**Children**");
    out.push("");
    out.push("| Element | Cardinality | Description |");
    out.push("|---|---|---|");
    for (const [, spec] of Object.entries(node.children)) {
      const card = `${spec.min ?? 0}..${spec.max ?? "∞"}`;
      out.push(`| \`<${spec.element}>\` | ${card} | ${spec.doc ?? ""} |`);
    }
    out.push("");
  }

  if (node.example) {
    out.push("**Example**");
    out.push("");
    out.push("```xml");
    out.push(node.example);
    out.push("```");
    out.push("");
  }

  return out;
}

function renderMeta(meta: CompiledMetaDefinition): string[] {
  const out: string[] = [];
  out.push(`### \`<${meta.tag}>\``);
  out.push("");
  if (meta.description) {
    out.push(meta.description);
    out.push("");
  }
  out.push(
    `Content model: \`${meta.contentModel}\`. ` +
      (meta.allowedParents.length > 0
        ? `Allowed parents: ${meta.allowedParents.map((p) => `\`<${p}>\``).join(", ")}.`
        : ""),
  );
  out.push("");

  const attrEntries = Object.entries(meta.attributes).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  if (attrEntries.length > 0) {
    out.push("**Attributes**");
    out.push("");
    out.push("| Name | Type | Required | Description |");
    out.push("|---|---|---|---|");
    for (const [name, spec] of attrEntries) {
      out.push(formatAttrRow(name, spec));
    }
    out.push("");
  }

  return out;
}

function formatAttrRow(name: string, spec: AttributeSpec): string {
  const type = spec.coerce + (spec.enum ? ` (${spec.enum.join("\\|")})` : "");
  const req = spec.required ? "yes" : "";
  let doc = spec.doc ?? "";
  if (spec.bodyAlias) {
    doc = (doc ? doc + " " : "") + "*(also accepted as element body text)*";
  }
  return `| \`${name}\` | ${type} | ${req} | ${doc} |`;
}

function anchor(tag: string): string {
  return tag.toLowerCase();
}
