/**
 * XSD generator — emits an XML Schema for the slideglance/builder XML
 * format under targetNamespace `urn:slideglance:builder:v1`.
 *
 * Output is deterministic so codegen verify can hash and diff it.
 */

import type {
  AttributeSpec,
  CompiledNodeDefinition,
} from "../registry/defineNode.ts";
import type { CompiledMetaDefinition } from "../registry/defineMeta.ts";
import { CHILD_ATTRIBUTE_SPECS } from "../parseXml/childAttributeSpecs.ts";
import { walkRegistry, coerceToXsdSimpleType } from "./walkRegistry.ts";

export const BUILDER_NAMESPACE_URI = "urn:slideglance:builder:v1";

/** Indented XML writer (no XML library — output is small and we want determinism). */
class XmlWriter {
  private readonly lines: string[] = [];
  private indent = 0;

  open(tag: string, attrs?: Record<string, string | undefined>): void {
    this.lines.push(`${this.pad()}${this.tag(tag, attrs, false)}`);
    this.indent += 1;
  }

  empty(tag: string, attrs?: Record<string, string | undefined>): void {
    this.lines.push(`${this.pad()}${this.tag(tag, attrs, true)}`);
  }

  close(tag: string): void {
    this.indent -= 1;
    this.lines.push(`${this.pad()}</${tag}>`);
  }

  comment(text: string): void {
    this.lines.push(`${this.pad()}<!-- ${escapeText(text)} -->`);
  }

  literal(line: string): void {
    this.lines.push(`${this.pad()}${line}`);
  }

  /** Emit `<tag>text</tag>` on one line. Used for tiny annotations. */
  textElement(
    tag: string,
    text: string,
    attrs?: Record<string, string | undefined>,
  ): void {
    const open = this.tag(tag, attrs, false);
    this.lines.push(`${this.pad()}${open}${escapeText(text)}</${tag}>`);
  }

  toString(): string {
    return this.lines.join("\n") + "\n";
  }

  private pad(): string {
    return "  ".repeat(this.indent);
  }

  private tag(
    tag: string,
    attrs: Record<string, string | undefined> | undefined,
    selfClose: boolean,
  ): string {
    let s = `<${tag}`;
    if (attrs) {
      for (const k of Object.keys(attrs).sort()) {
        const v = attrs[k];
        if (v === undefined) continue;
        s += ` ${k}="${escapeAttr(v)}"`;
      }
    }
    s += selfClose ? "/>" : ">";
    return s;
  }
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

function escapeText(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** Generate XSD source. */
export function generateXsd(): string {
  const registry = walkRegistry();
  const w = new XmlWriter();

  w.literal('<?xml version="1.0" encoding="UTF-8"?>');
  w.open("xs:schema", {
    "xmlns:xs": "http://www.w3.org/2001/XMLSchema",
    "xmlns:b": BUILDER_NAMESPACE_URI,
    xmlns: BUILDER_NAMESPACE_URI,
    targetNamespace: BUILDER_NAMESPACE_URI,
    elementFormDefault: "qualified",
    attributeFormDefault: "unqualified",
  });

  w.comment(
    "Generated by packages/builder/src/codegen/xsd.ts — do not edit by hand.",
  );

  // ---- Shared simpleTypes ----
  emitSharedSimpleTypes(w);

  // ---- Group: any builder node ----
  // Used as a child group by container nodes and by <Slide>/<Fragment>.
  w.open("xs:group", { name: "BuilderNodeGroup" });
  w.open("xs:choice");
  for (const tag of registry.nodeTags) {
    w.empty("xs:element", { ref: `b:${tag}` });
  }
  // Meta nodes that may appear inline:
  w.empty("xs:element", { ref: "b:Use" });
  w.empty("xs:element", { ref: "b:Import" });
  w.close("xs:choice");
  w.close("xs:group");

  // ---- Per-node complexTypes and elements ----
  for (const node of registry.nodes) {
    emitNodeType(w, node);
  }

  // ---- Per-meta complexTypes and elements ----
  for (const meta of registry.meta) {
    emitMetaType(w, meta);
  }

  // ---- Inline format elements inside <Text> ----
  emitInlineFormatTypes(w);

  // ---- <Master> and its child objects ----
  emitMasterTypes(w);

  w.close("xs:schema");
  return w.toString();
}

function emitSharedSimpleTypes(w: XmlWriter): void {
  // Boolean: enum "true"|"false"
  w.open("xs:simpleType", { name: "Boolean" });
  w.open("xs:restriction", { base: "xs:string" });
  w.empty("xs:enumeration", { value: "true" });
  w.empty("xs:enumeration", { value: "false" });
  w.close("xs:restriction");
  w.close("xs:simpleType");

  // Length: number, "{n}%", or "max"
  w.open("xs:simpleType", { name: "Length" });
  w.open("xs:union");
  w.open("xs:simpleType");
  w.empty("xs:restriction", { base: "xs:double" });
  w.close("xs:simpleType");
  w.open("xs:simpleType");
  w.open("xs:restriction", { base: "xs:string" });
  w.empty("xs:pattern", { value: "\\d+(\\.\\d+)?%|max" });
  w.close("xs:restriction");
  w.close("xs:simpleType");
  w.close("xs:union");
  w.close("xs:simpleType");

  // Color: hex (#abc, #aabbcc, #aabbccdd) or other string
  w.open("xs:simpleType", { name: "Color" });
  w.empty("xs:restriction", { base: "xs:string" });
  w.close("xs:simpleType");

  // Padding: number or JSON object string
  w.open("xs:simpleType", { name: "Padding" });
  w.open("xs:union");
  w.open("xs:simpleType");
  w.empty("xs:restriction", { base: "xs:double" });
  w.close("xs:simpleType");
  w.open("xs:simpleType");
  w.empty("xs:restriction", { base: "xs:string" });
  w.close("xs:simpleType");
  w.close("xs:union");
  w.close("xs:simpleType");

  // BorderStyle: shorthand string ("color w dash") or JSON object string
  w.open("xs:simpleType", { name: "BorderStyle" });
  w.empty("xs:restriction", { base: "xs:string" });
  w.close("xs:simpleType");

  // FillStyle, ShadowStyle, Underline, ImageSizing, LineArrow: JSON-ish strings
  for (const name of [
    "FillStyle",
    "ShadowStyle",
    "Underline",
    "ImageSizing",
    "LineArrow",
  ]) {
    w.open("xs:simpleType", { name });
    w.empty("xs:restriction", { base: "xs:string" });
    w.close("xs:simpleType");
  }

  // BorderDash, ShapeType, BulletNumberType, IconName, IconVariant: open enums (xs:string)
  for (const name of [
    "BorderDash",
    "ShapeType",
    "BulletNumberType",
    "IconName",
    "IconVariant",
  ]) {
    w.open("xs:simpleType", { name });
    w.empty("xs:restriction", { base: "xs:string" });
    w.close("xs:simpleType");
  }
}

const CONTAINER_CATEGORIES = new Set(["multi-child", "absolute-child"]);

function emitNodeType(w: XmlWriter, node: CompiledNodeDefinition): void {
  // complexType definition
  const isContainer =
    node.category !== undefined && CONTAINER_CATEGORIES.has(node.category);
  const isDocumentContainer =
    node.tag === "SlideGlance" ||
    node.tag === "Slide" ||
    node.tag === "Fragment";

  // Determine if this node has element body text (bodyAlias attribute)
  const bodyAliasName = Object.entries(node.attributes).find(
    ([, a]) => a.bodyAlias,
  )?.[0];

  const complexAttrs: Record<string, string | undefined> = {
    name: node.tag,
  };
  if (bodyAliasName !== undefined && !isContainer) {
    // Mixed content: text + (inline runs inside <Text> case)
    complexAttrs.mixed = "true";
  }

  w.open("xs:complexType", complexAttrs);
  if (node.description) {
    emitAnnotation(w, node.description);
  }

  // Children
  if (isContainer || isDocumentContainer) {
    emitContainerChildren(w, node);
  } else if (Object.keys(node.children).length > 0) {
    emitStructuredChildren(w, node);
  } else if (node.tag === "Text") {
    // Text accepts inline format children + mixed text
    w.open("xs:choice", { minOccurs: "0", maxOccurs: "unbounded" });
    for (const tag of ["B", "I", "U", "S", "Mark", "A", "Span"]) {
      w.empty("xs:element", { ref: `b:${tag}` });
    }
    w.close("xs:choice");
  }

  // Attributes
  emitAttributes(w, node.attributes);

  w.close("xs:complexType");

  // Element declaration
  w.empty("xs:element", { name: node.tag, type: `b:${node.tag}` });
}

function emitContainerChildren(
  w: XmlWriter,
  node: CompiledNodeDefinition,
): void {
  // SlideGlance: root-only children — Document, Master, Slide, Templates,
  // Styles, Import. <Document> carries the slide-size / default text style
  // settings; <Master> declares slide masters; the rest matches the
  // presentation-level surface.
  if (node.tag === "SlideGlance") {
    w.open("xs:choice", { minOccurs: "0", maxOccurs: "unbounded" });
    for (const ref of [
      "Document",
      "Master",
      "Slide",
      "Templates",
      "Styles",
      "Import",
    ]) {
      w.empty("xs:element", { ref: `b:${ref}` });
    }
    w.close("xs:choice");
    return;
  }
  // Slide / Fragment / VStack / HStack / Layer: any builder node
  w.open("xs:sequence");
  w.empty("xs:group", {
    ref: "b:BuilderNodeGroup",
    minOccurs: "0",
    maxOccurs: "unbounded",
  });
  w.close("xs:sequence");
}

function emitStructuredChildren(
  w: XmlWriter,
  node: CompiledNodeDefinition,
): void {
  w.open("xs:choice", { minOccurs: "0", maxOccurs: "unbounded" });
  for (const [, spec] of Object.entries(node.children)) {
    // Ensure the child element is referenceable. We declare it inline if it
    // isn't otherwise registered (Li, Row, Cell, Series, ...).
    w.empty("xs:element", { ref: `b:${spec.element}` });
  }
  // <Text> inline runs and special children for chart-like nodes are handled
  // as ad-hoc elements declared in emitInlineFormatTypes / emitStructuredChildElements.
  w.close("xs:choice");
}

const NUMERIC_DOT_FIELDS: Record<string, readonly string[]> = {
  padding: ["top", "right", "bottom", "left"],
  margin: ["top", "right", "bottom", "left"],
  border: [],
  fill: [],
  shadow: [],
  underline: [],
  cellBorder: [],
  cellMargin: ["top", "right", "bottom", "left"],
  beginArrow: [],
  endArrow: [],
  connectorStyle: [],
  sizing: [],
  backgroundImage: [],
};

function emitAttributes(
  w: XmlWriter,
  attrs: Record<string, AttributeSpec>,
): void {
  for (const name of Object.keys(attrs).sort()) {
    const a = attrs[name]!;
    emitAttribute(w, name, a);
    // Dot-notation virtual attributes (best-effort completion for editors)
    if (a.dotNotation) {
      const fields = NUMERIC_DOT_FIELDS[name] ?? [];
      for (const f of fields) {
        w.empty("xs:attribute", {
          name: `${name}.${f}`,
          type: "xs:double",
          use: "optional",
        });
      }
    }
  }
  // Universal class attribute (Styles support).
  w.empty("xs:attribute", {
    name: "class",
    type: "xs:string",
    use: "optional",
  });
}

function emitAttribute(w: XmlWriter, name: string, spec: AttributeSpec): void {
  const required = spec.required ? "required" : "optional";
  const xsdAttrs: Record<string, string | undefined> = { name, use: required };

  // Inline enum
  if (spec.enum && spec.enum.length > 0 && spec.coerce !== "iconName") {
    w.open("xs:attribute", xsdAttrs);
    if (spec.doc) emitAnnotation(w, spec.doc);
    w.open("xs:simpleType");
    w.open("xs:restriction", { base: "xs:string" });
    for (const v of spec.enum) {
      w.empty("xs:enumeration", { value: v });
    }
    w.close("xs:restriction");
    w.close("xs:simpleType");
    w.close("xs:attribute");
    return;
  }

  const mapped = coerceToXsdSimpleType(spec.coerce);
  xsdAttrs.type = mapped.named ?? mapped.primitive;

  if (spec.doc) {
    w.open("xs:attribute", xsdAttrs);
    emitAnnotation(w, spec.doc);
    w.close("xs:attribute");
  } else {
    w.empty("xs:attribute", xsdAttrs);
  }
}

function emitMetaType(w: XmlWriter, meta: CompiledMetaDefinition): void {
  w.open("xs:complexType", { name: meta.tag });
  if (meta.description) emitAnnotation(w, meta.description);

  switch (meta.contentModel) {
    case "any": {
      w.open("xs:sequence");
      w.empty("xs:group", {
        ref: "b:BuilderNodeGroup",
        minOccurs: "0",
        maxOccurs: "unbounded",
      });
      w.close("xs:sequence");
      break;
    }
    case "slots": {
      w.open("xs:sequence");
      w.empty("xs:element", {
        ref: "b:Slot",
        minOccurs: "0",
        maxOccurs: "unbounded",
      });
      w.close("xs:sequence");
      break;
    }
    case "templates": {
      w.open("xs:sequence");
      w.empty("xs:element", {
        ref: "b:Template",
        minOccurs: "0",
        maxOccurs: "unbounded",
      });
      w.close("xs:sequence");
      break;
    }
    case "styles": {
      w.open("xs:sequence");
      w.empty("xs:element", {
        ref: "b:Style",
        minOccurs: "0",
        maxOccurs: "unbounded",
      });
      w.close("xs:sequence");
      break;
    }
    case "none":
      // no children
      break;
  }

  emitAttributes(w, meta.attributes);
  // Open-attribute metas (e.g. <Style>) are untyped attribute bags at runtime
  // — every attribute is stored verbatim and merged into the element that
  // opts in via class="...", which validates them in its own context. Mirror
  // that by accepting any attribute here instead of rejecting valid presets.
  if (meta.openAttributes) {
    w.empty("xs:anyAttribute", { processContents: "skip" });
  }
  w.close("xs:complexType");
  w.empty("xs:element", { name: meta.tag, type: `b:${meta.tag}` });
}

/**
 * <Master> and its child objects (MasterText / MasterImage / MasterRect /
 * MasterLine / SlideNumber). These are not compiled registry nodes — they are
 * parsed via CHILD_ATTRIBUTE_SPECS at runtime — so the XSD declares them here,
 * driven by that same spec map. The SlideGlance root choice references
 * <Master>, so without these declarations the schema would not compile.
 */
function emitMasterTypes(w: XmlWriter): void {
  const masterChildren = [
    "MasterText",
    "MasterImage",
    "MasterRect",
    "MasterLine",
    "SlideNumber",
  ] as const;

  // <Master> container: a choice of master child objects plus its own attrs.
  w.open("xs:complexType", { name: "Master" });
  emitAnnotation(
    w,
    "Slide master — reusable background chrome (header / footer / page numbers / watermarks). Referenced by <Document defaultMaster> and per-slide `master`.",
  );
  w.open("xs:choice", { minOccurs: "0", maxOccurs: "unbounded" });
  for (const child of masterChildren) {
    w.empty("xs:element", { ref: `b:${child}` });
  }
  w.close("xs:choice");
  emitAttributes(w, CHILD_ATTRIBUTE_SPECS.Master ?? {});
  w.close("xs:complexType");
  w.empty("xs:element", { name: "Master", type: "b:Master" });

  // Master child objects — leaf elements with fixed attribute sets.
  for (const child of masterChildren) {
    w.open("xs:complexType", { name: child });
    emitAttributes(w, CHILD_ATTRIBUTE_SPECS[child] ?? {});
    w.close("xs:complexType");
    w.empty("xs:element", { name: child, type: `b:${child}` });
  }
}

function emitInlineFormatTypes(w: XmlWriter): void {
  // <B>/<I>/<U>/<S>/<Mark>/<A>/<Span> — inline format tags inside <Text>
  // Mixed content allowing nested inline tags.
  for (const tag of ["B", "I", "U", "S", "Mark", "A", "Span"]) {
    w.open("xs:complexType", { name: tag, mixed: "true" });
    w.open("xs:choice", { minOccurs: "0", maxOccurs: "unbounded" });
    for (const inner of ["B", "I", "U", "S", "Mark", "A", "Span"]) {
      w.empty("xs:element", { ref: `b:${inner}` });
    }
    w.close("xs:choice");
    if (tag === "A") {
      w.empty("xs:attribute", { name: "href", type: "xs:string" });
    }
    if (tag === "Span") {
      w.empty("xs:attribute", { name: "color", type: "b:Color" });
      w.empty("xs:attribute", { name: "highlight", type: "b:Color" });
      w.empty("xs:attribute", { name: "lang", type: "xs:string" });
    }
    w.close("xs:complexType");
    w.empty("xs:element", { name: tag, type: `b:${tag}` });
  }

  // Structured child elements declared via children specs but not as nodes:
  // Li, Col, Tr, Td, ChartSeries, ChartDataPoint.
  emitStructuredChildElement(w, "Li", { mixed: true });
  emitStructuredChildElement(w, "Col", { mixed: false });
  emitStructuredChildElement(w, "Tr", { children: ["Td"] });
  emitStructuredChildElement(w, "Td", { mixed: true });
  emitStructuredChildElement(w, "ChartSeries", {
    children: ["ChartDataPoint"],
  });
  emitStructuredChildElement(w, "ChartDataPoint", { mixed: false });

  // <svg> child of <Svg> — permissive content model so authors can paste
  // any SVG markup. We accept any sub-elements / attributes.
  w.open("xs:element", { name: "svg" });
  w.open("xs:complexType", { mixed: "true" });
  w.open("xs:sequence");
  w.empty("xs:any", {
    namespace: "##any",
    minOccurs: "0",
    maxOccurs: "unbounded",
    processContents: "skip",
  });
  w.close("xs:sequence");
  w.empty("xs:anyAttribute", { processContents: "skip" });
  w.close("xs:complexType");
  w.close("xs:element");
}

function emitStructuredChildElement(
  w: XmlWriter,
  tag: string,
  options: { mixed?: boolean; children?: readonly string[] },
): void {
  const attrs: Record<string, string | undefined> = { name: tag };
  if (options.mixed) attrs.mixed = "true";
  w.open("xs:complexType", attrs);
  if (options.children && options.children.length > 0) {
    w.open("xs:sequence");
    for (const c of options.children) {
      w.empty("xs:element", {
        ref: `b:${c}`,
        minOccurs: "0",
        maxOccurs: "unbounded",
      });
    }
    w.close("xs:sequence");
  }
  w.empty("xs:anyAttribute", { processContents: "skip" });
  w.close("xs:complexType");
  w.empty("xs:element", { name: tag, type: `b:${tag}` });
}

function emitAnnotation(w: XmlWriter, doc: string): void {
  w.open("xs:annotation");
  w.textElement("xs:documentation", doc);
  w.close("xs:annotation");
}
