import { buildPptx } from "../../src/index.js";
import {
  palette,
  page1TextXml,
  page2ListXml,
  page3ImageXml,
  page3bImageSizingXml,
  page4TableXml,
  page5ShapeXml,
  page6ChartXml,
  page7LayoutXml,
  page8CommonXml,
  page10ChartAdditionalXml,
  page15LineXml,
  page16LayerXml,
  page17HStackTableXml,
  page18OpacityXml,
  page19ShadowXml,
  page20BackgroundImageXml,
  page21XmlChildElementsXml,
  page23TableColspanRowspanXml,
  page25IconXml,
  page26VStackHStackShadowXml,
  page27HStackFlexShrinkXml,
  page28LayoutV2Xml,
  page29IconInHStackXml,
  page30LeafPaddingXml,
  page31LeafPaddingCompositeXml,
  page32CenterAlignHStackXml,
  page33CustomFontXml,
  page34CustomFontWrapXml,
  page35SvgNodeXml,
  page36InlineFormattingXml,
  page37TableCellBorderXml,
  page38D4SchemaAdditionsXml,
  pageConnectorXml,
} from "./slides/index.js";

export async function generatePptx(outputPath: string): Promise<void> {
  const allPagesXml = [
    page1TextXml,
    page2ListXml,
    page3ImageXml,
    page3bImageSizingXml,
    page4TableXml,
    page5ShapeXml,
    page6ChartXml,
    page7LayoutXml,
    page8CommonXml,
    page10ChartAdditionalXml,
    page15LineXml,
    page16LayerXml,
    page17HStackTableXml,
    page18OpacityXml,
    page19ShadowXml,
    page20BackgroundImageXml,
    page21XmlChildElementsXml,
    page23TableColspanRowspanXml,
    page25IconXml,
    page26VStackHStackShadowXml,
    page27HStackFlexShrinkXml,
    page28LayoutV2Xml,
    page29IconInHStackXml,
    page30LeafPaddingXml,
    page31LeafPaddingCompositeXml,
    page32CenterAlignHStackXml,
    page33CustomFontXml,
    page34CustomFontWrapXml,
    page35SvgNodeXml,
    page36InlineFormattingXml,
    page37TableCellBorderXml,
    page38D4SchemaAdditionsXml,
    pageConnectorXml,
  ].join("\n");

  const { pptx } = await buildPptx(
    allPagesXml,
    {
      w: 1280,
      h: 720,
    },
    {
      textMeasurement: "fallback",
      master: {
        title: "VRT_MASTER",
        objects: [
          // Header background.
          {
            type: "rect",
            x: 0,
            y: 0,
            w: 1280,
            h: 40,
            fill: { color: palette.navy },
          },
          // Header text (left).
          {
            type: "text",
            text: "VRT Test Suite",
            x: 48,
            y: 12,
            w: 200,
            h: 28,
            fontSize: 14,
            color: "FFFFFF",
          },
          // Header text (right) — fixed date.
          {
            type: "text",
            text: "2025/01/01",
            x: 1032,
            y: 12,
            w: 200,
            h: 28,
            fontSize: 12,
            color: "E2E8F0",
            textAlign: "right",
          },
          // Footer text (left).
          {
            type: "text",
            text: "pom VRT",
            x: 48,
            y: 682,
            w: 200,
            h: 30,
            fontSize: 10,
            color: palette.charcoal,
          },
        ],
        slideNumber: {
          x: 1032,
          y: 682,
          w: 200,
          h: 30,
          fontSize: 10,
          color: palette.charcoal,
        },
      },
    },
  );

  await pptx.writeFile({ fileName: outputPath });
}
